Repository reactioncommerce/reaction, pull requests merged in 2018-11, with the labels that each got.

#4767 Address validation GraphQL
  client/modules/core/helpers/templates.js
  imports/plugins/core/accounts/client/components/addressBook.js
  imports/plugins/core/accounts/client/containers/addressBookContainer.js
  imports/plugins/core/accounts/server/methods/validateAddress.js
  imports/plugins/core/address/client/components/AddressValidationSettingsForm.js
  imports/plugins/core/address/client/components/ShopAddressValidationSettings.js
  imports/plugins/core/address/client/containers/ShopAddressValidationSettings.js
  imports/plugins/core/address/client/hoc/withAddressValidationServices.js
  imports/plugins/core/address/client/index.js
  imports/plugins/core/address/register.js
  imports/plugins/core/address/server/i18n/en.json
  imports/plugins/core/address/server/i18n/index.js
  imports/plugins/core/address/server/index.js
  imports/plugins/core/address/server/no-meteor/queries/addressValidation.js
  imports/plugins/core/address/server/no-meteor/queries/addressValidationServices.js
  imports/plugins/core/address/server/no-meteor/queries/index.js
  imports/plugins/core/address/server/no-meteor/registration.js
  imports/plugins/core/address/server/no-meteor/resolvers/Query/addressValidation.js
  imports/plugins/core/address/server/no-meteor/resolvers/Query/addressValidationServices.js
  imports/plugins/core/address/server/no-meteor/resolvers/Query/index.js
  imports/plugins/core/address/server/no-meteor/resolvers/index.js
  imports/plugins/core/address/server/no-meteor/schemas/index.js
  imports/plugins/core/address/server/no-meteor/schemas/schema.graphql
  imports/plugins/core/core/server/Reaction/core.js
  imports/plugins/core/core/server/methods/updatePackage.js
  imports/plugins/core/core/server/no-meteor/schemas/address.graphql
  imports/plugins/core/dashboard/client/templates/shop/settings/settings.html
  imports/plugins/core/dashboard/client/templates/shop/settings/settings.js
  imports/plugins/core/payments/client/checkout/payment/methods.js
  imports/plugins/core/router/client/appComponents.js
  imports/plugins/core/shipping/client/templates/settings/shipping.js
  imports/plugins/core/ui/client/helpers/react-template-helper.js
  imports/plugins/included/address-validation-test/README.md
  imports/plugins/included/address-validation-test/register.js
  imports/plugins/included/address-validation-test/server/addressValidation.js
  package-lock.json
  package.json
Labels: solution-engineering

#4805 feat: Put mongo on the streams network
  .reaction/waitForMongo.js
  docker-compose.yml
Labels: enhancements, impact-minor

#4811 Fix tax calculation arguments, other tax fixes
  imports/collections/schemas/cart.js
  imports/plugins/core/cart/server/no-meteor/mutations/convertAnonymousCartToNewAccountCart.test.js
  imports/plugins/core/cart/server/no-meteor/mutations/createCart.test.js
  imports/plugins/core/cart/server/no-meteor/mutations/reconcileCartsKeepAnonymousCart.test.js
  imports/plugins/core/cart/server/no-meteor/mutations/reconcileCartsMerge.js
  imports/plugins/core/cart/server/no-meteor/mutations/reconcileCartsMerge.test.js
  imports/plugins/core/cart/server/no-meteor/mutations/updateCartItemsQuantity.js
  imports/plugins/core/cart/server/no-meteor/mutations/updateCartItemsQuantity.test.js
  imports/plugins/core/cart/server/no-meteor/startup.js
  imports/plugins/core/cart/server/no-meteor/util/addCartItems.js
  imports/plugins/core/cart/server/no-meteor/util/updateCartItemsForVariantPriceChange.js
  imports/plugins/core/cart/server/no-meteor/util/xformCartGroupToCommonOrder.js
  imports/plugins/core/catalog/server/no-meteor/utils/publishProductToCatalog.js
  imports/plugins/core/core/server/fixtures/cart.js
  imports/plugins/core/graphql/server/no-meteor/xforms/cart.js
  imports/plugins/core/orders/server/no-meteor/mutations/createOrder.js
  imports/plugins/core/orders/server/no-meteor/simpleSchemas.js
  imports/plugins/core/orders/server/util/xformOrderGroupToCommonOrder.js
  imports/plugins/core/taxes/lib/simpleSchemas.js
  imports/plugins/core/taxes/server/no-meteor/mutations/getFulfillmentGroupTaxes.js
  imports/plugins/core/taxes/server/no-meteor/schemas/schema.graphql
  imports/plugins/core/taxes/server/no-meteor/startup.js
  imports/plugins/core/versions/server/migrations/46_cart_item_props.js
  imports/plugins/core/versions/server/migrations/index.js
  imports/plugins/core/versions/server/util/findVariantInCatalogProduct.js
  imports/plugins/included/discount-codes/server/no-meteor/util/getItemPriceDiscount.js
  imports/plugins/included/discount-codes/server/no-meteor/util/getPercentageOffDiscount.js
  imports/plugins/included/marketplace/server/no-meteor/mutations/placeMarketplaceOrderWithStripeCardPayment.js
  imports/plugins/included/payments-example/server/no-meteor/mutations/placeOrderWithExampleIOUPayment.js
  imports/plugins/included/payments-stripe/server/no-meteor/mutations/placeOrderWithStripeCardPayment.js
  imports/plugins/included/taxes-rates/register.js
  imports/plugins/included/taxes-rates/server/no-meteor/util/calculateOrderTaxes.js
  lib/collections/transform/cartOrder.js
Labels: solution-engineering

#4742 fix: 4741 catalog variant inventory flags always false
  imports/plugins/core/catalog/server/no-meteor/utils/createCatalogProduct.js
  imports/plugins/core/catalog/server/no-meteor/utils/createCatalogProduct.test.js
  imports/plugins/core/catalog/server/no-meteor/utils/updateCatalogProductInventoryStatus.js
  imports/plugins/core/catalog/server/no-meteor/utils/updateCatalogProductInventoryStatus.test.js
  imports/plugins/core/versions/server/migrations/48_catalog_variant_inventory.js
  imports/plugins/core/versions/server/migrations/index.js
  imports/plugins/core/versions/server/util/convert48.js
  imports/plugins/core/versions/server/util/convert48.test.js
  imports/test-utils/helpers/mockContext.js
Labels: solution-engineering

#4819 Add a mongodb index on Catalog.updatedAt
  lib/collections/collections.js
Labels: performance

#4795 Fix identity provider login page not found due to missing permission
  imports/plugins/core/hydra-oauth/server/index.js
Labels: blocked
