Repository reactioncommerce/reaction, pull requests merged in 2018-07, with the labels that each got.

#4402 Fix #4374: not publishing customer accounts
  imports/plugins/core/core/server/publications/collections/accounts.js
Labels: performance

#4182 Fix #4141: Options now have parent's taxCode
  imports/plugins/core/catalog/client/containers/publishContainer.js
  imports/plugins/core/catalog/server/methods/catalog.js
  imports/plugins/core/taxes/server/methods/methods.js
Labels: impact-minor

#4140 Fix 4089: Taxcloud with marketplace setup.
  imports/collections/schemas/cart.js
  imports/plugins/core/orders/client/containers/invoiceContainer.js
  imports/plugins/core/taxes/server/methods/methods.js
  imports/plugins/included/product-variant/containers/variantFormContainer.js
  imports/plugins/included/taxes-taxcloud/client/containers/taxCloudSettingsFormContainer.js
  imports/plugins/included/taxes-taxcloud/lib/collections/schemas/schema.js
  imports/plugins/included/taxes-taxcloud/register.js
  imports/plugins/included/taxes-taxcloud/server/hooks/hooks.js
  imports/plugins/included/taxes-taxcloud/server/i18n/en.json
  imports/plugins/included/taxes-taxcloud/server/index.js
  imports/plugins/included/taxes-taxcloud/server/jobs/index.js
  imports/plugins/included/taxes-taxcloud/server/jobs/taxcodes.js
  imports/plugins/included/taxes-taxcloud/server/methods/methods.js
  tests/meteor/cart-remove.app-test.js
Labels: integrations

#4086 Shippo address validation
  imports/collections/schemas/address.js
  imports/plugins/core/accounts/client/components/addressBook.js
  imports/plugins/core/accounts/client/containers/addressBookContainer.js
  imports/plugins/core/accounts/server/methods/validateAddress.js
  imports/plugins/included/shipping-shippo/register.js
  imports/plugins/included/shipping-shippo/server/methods/shippo.js
  imports/plugins/included/shipping-shippo/server/methods/shippoapi.js
Labels: impact-critical

#3332 Consideration for Marketplace Shops on Different URLs
  client/modules/core/domains.js
  client/modules/core/domains.test.js
  client/modules/core/main.js
  client/modules/router/helpers.js
  imports/plugins/core/accounts/server/methods/inviteShopMember.js
  imports/plugins/core/accounts/server/methods/removeEmailAddress.js
  imports/plugins/core/accounts/server/methods/sendResetPasswordEmail.js
  imports/plugins/core/accounts/server/methods/sendWelcomeEmail.js
  imports/plugins/core/accounts/server/util/getDataForEmail.js
  imports/plugins/core/core/server/Reaction/Email/getShopLogo.js
  imports/plugins/core/core/server/Reaction/Email/send.js
  imports/plugins/core/core/server/Reaction/absoluteUrl.app-test.js
  imports/plugins/core/core/server/Reaction/absoluteUrl.js
  imports/plugins/core/core/server/Reaction/core.app-test.js
  imports/plugins/core/core/server/Reaction/core.js
  imports/plugins/core/core/server/Reaction/sendVerificationEmail.js
  imports/plugins/core/core/server/startup/browser-policy.js
  imports/plugins/core/files/client/index.js
  imports/plugins/core/files/server/fileCollections.js
  imports/plugins/core/job-collection/lib/jobCollection.app-test.js
  imports/plugins/core/orders/server/util/sendOrderEmail.js
  lib/api/helpers.js
  lib/core/url-common.app-test.js
  lib/core/url-common.js
Labels: community

#4427 GraphQL: Add accountCartByAccountId resolver
  imports/plugins/core/cart/server/no-meteor/mutations/createCart.test.js
  imports/plugins/core/cart/server/no-meteor/queries/__snapshots__/accountCartByAccountId.test.js.snap
  imports/plugins/core/cart/server/no-meteor/queries/accountCartByAccountId.js
  imports/plugins/core/cart/server/no-meteor/queries/accountCartByAccountId.test.js
  imports/plugins/core/cart/server/no-meteor/queries/anonymousCartByCartId.js
  imports/plugins/core/cart/server/no-meteor/queries/index.js
  imports/plugins/core/graphql/server/no-meteor/buildContext.test.js
  imports/plugins/core/graphql/server/no-meteor/resolvers/cart/Query/accountCartByAccountId.js
  imports/plugins/core/graphql/server/no-meteor/resolvers/cart/Query/accountCartByAccountId.test.js
  imports/plugins/core/graphql/server/no-meteor/resolvers/cart/Query/anonymousCartByCartId.js
  imports/plugins/core/graphql/server/no-meteor/resolvers/cart/Query/index.js
  imports/test-utils/helpers/mockContext.js
Labels: enhancements
