Repository reactioncommerce/reaction, pull requests merged in 2018-02, with the labels that each got.

#3643 Add missing address2 details
  imports/plugins/core/checkout/client/components/completedOrder.js
  server/methods/core/orders.js
Labels: community

#3806 Fixes #3805: remove spinner before mounting
  imports/plugins/core/accounts/client/components/updatePasswordOverlay.js
Labels: impact-critical

#3787 Update en.json
  imports/plugins/core/accounts/server/i18n/en.json
Labels: community

#3848 Call OrdersList as a Component
  imports/plugins/core/accounts/client/templates/profile/userOrdersList.js
Labels: community, impact-minor

#3845 (Fix 3836) Fix invite shop owner
  server/api/core/core.js
  server/api/core/groups.js
  server/methods/accounts/accounts.js
  server/methods/core/shop.js
Labels: impact-critical

#3835 Fix for "Changing user currency does not update prices"
  imports/plugins/included/jobcontrol/server/jobs/cart.js
  imports/plugins/included/jobcontrol/server/jobs/cleanup.js
  imports/plugins/included/jobcontrol/server/jobs/exchangerates.js
Labels: impact-critical

#3807 Fixes #3692: bulk order status corrected
  imports/plugins/core/orders/client/components/orderBulkActionsBar.js
  imports/plugins/core/orders/client/containers/orderTableContainer.js
Labels: impact-major

#3745 Fixes #2736: added unique to slug
  lib/collections/schemas/shops.js
  server/imports/fixtures/shops.js
Labels: impact-major

#3529 [Feature Request] Allow for ShopId when adding Brand Assets
  private/data/i18n/en.json
  server/methods/core/shop.js
Labels: community
