Repository reactioncommerce/reaction, pull requests merged in 2018-06, with the labels that each got.

#3841 docs(jsdoc): #3840 document all Meteor Template helpers in 1 @namespace
  client/modules/core/helpers/apps.js
  client/modules/core/helpers/layout.js
  client/modules/core/helpers/permissions.js
  client/modules/core/helpers/templates.js
  client/modules/i18n/helpers.js
  client/modules/router/helpers.js
  imports/plugins/core/accounts/client/helpers/templates.js
  imports/plugins/core/accounts/client/templates/dropdown/helpers/templates.js
  imports/plugins/core/checkout/client/helpers/cart.js
  imports/plugins/core/ui-tagnav/client/helpers/tags.js
Labels: impact-minor

#4259 [4092] Bug Fix: Product Visibility for Marketplace Shops
  imports/plugins/included/product-variant/containers/productsContainerCustomer.js
  server/publications/collections/orders-publications.app-test.js
Labels: community, impact-major

#4206 Limit Tags Publication to Those for the Current Shop
  client/modules/core/main.js
  imports/plugins/core/ui/client/containers/tagListContainer.js
  imports/plugins/included/product-admin/client/containers/productAdmin.js
  imports/plugins/included/product-detail-simple/client/containers/productDetail.js
  server/api/core/core.app-test.js
  server/api/core/core.js
  server/publications/collections/tags.app-test.js
  server/publications/collections/tags.js
Labels: community

#4083 Default settings for parcel size
  imports/collections/schemas/shops.js
  imports/plugins/core/i18n/client/containers/localizationSettings.js
  imports/plugins/core/shipping/client/components/index.js
  imports/plugins/core/shipping/client/components/parcelSizeSettings.js
  imports/plugins/core/shipping/client/containers/index.js
  imports/plugins/core/shipping/client/containers/parcelSizeSettings.js
  imports/plugins/core/shipping/client/index.js
  imports/plugins/core/shipping/client/templates/settings/shipping.html
  imports/plugins/core/shipping/client/templates/settings/shipping.js
  imports/plugins/core/shipping/server/i18n/en.json
  imports/plugins/core/shipping/server/methods/methods.js
  imports/plugins/core/versions/server/migrations/27_add_hash_to_products.js
  imports/plugins/core/versions/server/migrations/29_default_parcel_size.js
  imports/plugins/core/versions/server/migrations/index.js
  imports/plugins/included/default-theme/client/styles/dashboard/shippingConfig.less
  lib/api/helpers.js
  private/data/Shops.json
  server/imports/fixtures/products.js
  server/imports/fixtures/shops.js
  server/methods/core/cart.js
Labels: integrations
