Repository reactioncommerce/reaction, pull requests merged in 2018-03, with the labels that each got.

#3748 Fix: Changing the permalink before publishing a product results in "not found"
  imports/plugins/included/product-variant/client/templates/products/productSettings/productSettings.js
Labels: impact-minor

#3751 Fixes 3597: adding country code to phone number before sending SMS
  imports/plugins/included/sms/server/methods/sms.js
  lib/api/helpers.js
Labels: impact-minor

#3794 Fixes #2810: /shop added to URL
  client/modules/core/main.js
  imports/plugins/core/router/lib/router.js
  imports/plugins/core/versions/server/migrations/20_add_shop_to_marketplace.js
  imports/plugins/core/versions/server/migrations/index.js
  imports/plugins/included/marketplace/register.js
  server/api/core/core.js
Labels: impact-minor

#3809 (fix: 3619) Fix for: Shop switcher opens off-screen
  imports/plugins/core/ui/client/components/popover/popover.js
Labels: impact-major

#3822 (fix: 3705) Fix for "capturing bulk orders throws server side error"
  imports/plugins/core/orders/client/containers/orderTableContainer.js
Labels: impact-major

#3827 (Fix 3813) Handle misconfigured Avalara api
  imports/plugins/included/taxes-avalara/server/hooks/hooks.js
  imports/plugins/included/taxes-avalara/server/methods/taxCalc.js
  server/methods/accounts/accounts.js
Labels: impact-minor

#3856 (fix: 3846) Set localstorage even when no Meteor.user exists
  client/modules/core/main.js
Labels: impact-critical

#3860 Fix 3854: password validation
  lib/api/account-validation.js
Labels: impact-major

#3869 (fix 3868) Remove cfs:graphicsmagick
  .meteor/packages
  .meteor/versions
Labels: impact-major

#3874 docs(jsdoc) #3840 - document and namespace Router.Hooks methods
  imports/plugins/core/router/lib/hooks.js
Labels: impact-minor

#3824 (fix: 3783) Discount codes limits are not honored
  imports/plugins/core/discounts/client/components/list.js
  server/methods/core/cart.js
  server/methods/core/payments.js
Labels: impact-major

#3894 (Fix) Add back missing browser policy
  imports/plugins/core/ui/server/index.js
  imports/plugins/core/ui/server/policy.js
Labels: impact-major

#3796 Fixes #2863: added delay and loader
  imports/plugins/core/checkout/client/components/cartSubTotal.js
  imports/plugins/core/checkout/client/containers/cartSubTotalContainer.js
  imports/plugins/included/default-theme/client/styles/cart/cartSubTotals.less
Labels: impact-major

#3837 (fix:) Issue #3797 — Removing search-mongo plugin causes errors at startup
  imports/plugins/core/versions/server/migrations/14_rebuild_order_search_collection.js
  imports/plugins/core/versions/server/migrations/1_rebuild_account_and_order_search_collections.js
Labels: community, impact-minor

#3755 Fix 2246: Setting or changing a products perma-link causes hard refresh
  client/modules/core/main.js
  imports/plugins/core/revisions/client/containers/publishContainer.js
  imports/plugins/core/revisions/server/methods.js
  imports/plugins/included/product-detail-simple/client/containers/productDetail.js
  imports/plugins/included/product-detail-simple/client/containers/publish.js
  lib/api/products.js
  lib/collections/schemas/products.js
  server/publications/collections/product.js
  server/publications/collections/products.js
Labels: impact-minor

#3932 Fix for ui glitches using dynamic merchandising
  imports/plugins/core/ui/client/containers/sortableItem.js
  imports/plugins/included/product-variant/containers/productGridContainer.js
Labels: bug, impact-major

#3947 Fix 3945: update shopId the right way.
  client/modules/core/main.js
  client/modules/core/startup.js
Labels: impact-critical

#3884 Fix for `Change all email verification links to use tokens`
  imports/plugins/core/accounts/client/components/verifyAccount.js
  imports/plugins/core/accounts/client/containers/passwordOverlay.js
  imports/plugins/core/accounts/client/containers/verifyAccount.js
  imports/plugins/core/accounts/client/index.js
  imports/plugins/core/accounts/client/templates/updatePassword/updatePassword.js
  imports/plugins/core/accounts/client/templates/verify/verifyAccount.html
  imports/plugins/core/accounts/client/templates/verify/verifyAccount.js
  imports/plugins/core/accounts/register.js
  imports/plugins/core/versions/server/migrations/22_register_verify_account.js
  imports/plugins/core/versions/server/migrations/index.js
  imports/plugins/included/default-theme/client/styles/dashboard/accounts.less
  private/data/i18n/de.json
  private/data/i18n/en.json
  server/api/core/core.js
  server/methods/accounts/accounts.js
  server/startup/accounts.js
Labels: bug, impact-major

#3899 Fix #3733: email validation
  imports/plugins/core/accounts/client/components/loginInline.js
  imports/plugins/included/default-theme/client/styles/cart/checkout.less
  lib/api/helpers.js
  private/data/i18n/en.json
Labels: impact-major

#3897 Fix #3718: Inventory updated on shopify sync
  imports/plugins/included/connectors-shopify/server/endpoints/webhooks.js
  imports/plugins/included/connectors-shopify/server/methods/sync/orders.js
Labels: impact-major

#3948 Console error during checkout
  imports/plugins/core/checkout/client/containers/cartSubTotalContainer.js
Labels: bug, impact-major

#3892 Fix #3875: card validator
  imports/plugins/included/payments-authnet/server/methods/authnet.js
  imports/plugins/included/payments-example/server/methods/example.js
  lib/api/helpers.js
Labels: impact-major

#3859 Fix #1236: break payment before sending to paypal
  imports/plugins/included/payments-paypal/server/methods/express.js
Labels: impact-minor

#3943 Fix #3942: publishing group related to current shop
  imports/plugins/core/accounts/client/containers/accountsDashboardContainer.js
Labels: impact-major

#3896 (Fix 3895) Fix global route hooks
  imports/plugins/core/router/lib/hooks.js
Labels: impact-minor

#3970 Fix for "Reactivity error when products are not published yet"
  server/publications/collections/product.js
  server/publications/collections/products.js
Labels: impact-major

#3984 Fix for "dirty badge in product grid does not work"
  imports/plugins/included/product-variant/containers/productsContainer.js
  server/publications/collections/products.js
Labels: bug, impact-major, regression

#3989 Fix for "Summary not shown in Invoice"
  imports/plugins/core/orders/client/templates/list/pdf.js
Labels: impact-major

#3981 Fix #3979 marketplace shipping
  imports/plugins/included/search-mongo/server/methods/searchcollections.js
Labels: impact-critical

#3983 Fix #3965: Check for number if sms is enabled.
  imports/plugins/included/sms/server/methods/sms.js
  lib/api/helpers.js
Labels: impact-major

#3993 Fix for "PDP Image gallery does not handle portrait sized images well"
  imports/plugins/core/ui/client/components/media/mediaGallery.js
  imports/plugins/included/default-theme/client/styles/media.less
Labels: bug, design-review, impact-major

#3980 Fix for "Browser console warning when beginning checkout"
  imports/plugins/included/product-detail-simple/client/containers/productDetail.js
Labels: bug, impact-major, regression

#3844 docs(jsdoc): #3840 namespace MethodHooks into its own JSDoc section.
  server/api/method-hooks.js
Labels: impact-minor

#3825 Remove collection hooks for Products collection
  imports/plugins/core/checkout/server/methods/workflow.js
  imports/plugins/core/discounts/server/hooks/cart.js
  imports/plugins/core/orders/server/startup.js
  imports/plugins/core/revisions/server/functions.js
  imports/plugins/core/revisions/server/hooks.js
  imports/plugins/core/revisions/server/methods.js
  imports/plugins/core/taxes/server/hooks/taxes.js
  imports/plugins/included/connectors-shopify/server/hooks/orders.js
  server/imports/fixtures/products.js
  server/methods/catalog.app-test.js
  server/methods/catalog.js
  server/methods/core/cart-merge.app-test.js
  server/methods/core/cart.js
Labels: performance

#3510 [#3507] Memoize/Cache getShopId to Reduce DB Load
  client/modules/core/main.js
  server/api/core/connectionDataStore.app-test.js
  server/api/core/connectionDataStore.js
  server/api/core/core.app-test.js
  server/api/core/core.js
  server/methods/core/shop.js
  server/publications/collections/orders.js
  server/startup/collection-security.js
Labels: community, performance

#4000 Fix #3975: typo fix
  imports/plugins/included/connectors-shopify/client/settings/shopify.html
Labels: impact-minor, regression

#4027 Fix for "ProductGridItem (user role) is not replaceable
  imports/plugins/included/product-variant/client/index.js
  imports/plugins/included/product-variant/components/customer/productGrid.js
  imports/plugins/included/product-variant/components/customer/productGridItem.js
  imports/plugins/included/product-variant/containers/productsContainerCustomer.js
Labels: bug, enhancements, impact-major

#4025 Fix for "ProductsContainerAdmin and ProductsContainerCustomer are not…
  imports/plugins/included/product-variant/containers/productsContainer.js
Labels: bug, enhancements, impact-major

#3964 Fix for: Cloning products is not reactive
  imports/plugins/included/product-variant/containers/productsContainerAdmin.js
  lib/api/products.js
Labels: bug, impact-major, regression

#4044 Fix for Multiple instances of Components.Login causes a browser warning because ids are identical
  imports/plugins/core/accounts/client/components/login.js
Labels: bug, impact-minor

#3885 Fix #3754: check permission before publish
  lib/api/core.js
  server/publications/collections/shops.js
Labels: impact-minor

#3795 Fix: Credit card accepts invalid expiration date
  client/modules/i18n/startup.js
Labels: bug, impact-minor

#3873 docs: #3840 jsdoc - document fixtures
  lib/api/router/metadata.js
  server/imports/fixtures/accounts.js
  server/imports/fixtures/cart.js
  server/imports/fixtures/groups.js
  server/imports/fixtures/index.js
  server/imports/fixtures/orders.js
  server/imports/fixtures/packages.js
  server/imports/fixtures/products.js
  server/imports/fixtures/shops.js
  server/imports/fixtures/users.js
  server/methods/core/packages.js
  server/startup/i18n.js
Labels: impact-minor

#3842 docs(jsdoc): #3840 DOM module - add @memberof, @method
  imports/plugins/core/dom/client/dom.js
Labels: impact-minor
