Repository reactioncommerce/reaction, pull requests merged in 2018-10, with the labels that each got.

#4697 fix: 4694 nnnnat edit groups panel
  imports/plugins/core/accounts/client/components/editGroup.js
Labels: bug

#4704 fix: resolve errors in jsdoc Promise returns
  imports/plugins/core/cart/client/util/buildOrderInputFromCart.js
  imports/plugins/core/graphql/server/no-meteor/xforms/connection.js
Labels: bug

#4425 Bug Fix: Product Visibility for Marketplace Shops 2
  imports/plugins/included/product-variant/containers/productsContainerAdmin.js
Labels: community

#4715 feature: add product tags to cart items
  imports/collections/schemas/cart.js
  imports/plugins/core/cart/server/no-meteor/resolvers/CartItem/index.js
  imports/plugins/core/cart/server/no-meteor/resolvers/CartItem/productTags.js
  imports/plugins/core/cart/server/no-meteor/schemas/cart.graphql
  imports/plugins/core/cart/server/no-meteor/util/addCartItems.js
  imports/plugins/core/core/server/startup/startNodeApp.js
Labels: enhancements

#4751 chore: Skip failing integration tests
  package.json
  tests/account/account.test.js
  tests/account/addAccountAddressBookEntry.test.js
  tests/account/administrators.test.js
  tests/account/group.test.js
  tests/account/groups.test.js
  tests/account/viewer.test.js
  tests/catalog/catalogItemProduct.test.js
  tests/catalog/catalogItems.test.js
  tests/catalog/publishProductsToCatalog.test.js
  tests/shop/primaryShopId.test.js
  tests/shop/shop.test.js
  tests/tag/tags.test.js
Labels: chore

#4740 feat: decouple SMTP email sending logic from core to allow plugins to override
  imports/plugins/core/core/server/Reaction/processEmailJobs.js
  imports/plugins/core/email/client/components/EmailConfig.js
  imports/plugins/core/email/client/containers/EmailConfigContainer.js
  imports/plugins/core/email/client/index.js
  imports/plugins/core/email/client/templates/email.js
  imports/plugins/core/email/server/index.js
  imports/plugins/included/email-smtp/client/actions/index.js
  imports/plugins/included/email-smtp/client/actions/settings.js
  imports/plugins/included/email-smtp/client/components/SMTPEmailConfig.js
  imports/plugins/included/email-smtp/client/components/SMTPEmailSettings.js
  imports/plugins/included/email-smtp/client/containers/SMTPEmailConfigContainer.js
  imports/plugins/included/email-smtp/client/containers/SMTPEmailSettingsContainer.js
  imports/plugins/included/email-smtp/client/index.js
  imports/plugins/included/email-smtp/register.js
  imports/plugins/included/email-smtp/server/index.js
  imports/plugins/included/email-smtp/server/methods/index.js
  imports/plugins/included/email-smtp/server/methods/retryFailed.js
  imports/plugins/included/email-smtp/server/methods/saveSettings.js
  imports/plugins/included/email-smtp/server/methods/verifySettings.js
  imports/plugins/included/email-smtp/server/startup.js
  imports/plugins/included/email-smtp/server/util/sendSMTPEmail.js
Labels: solution-engineering
