Repository reactioncommerce/reaction, pull requests merged in 2018-04, with the labels that each got.

#3999 Fix #3821: use numericInput for pricing
  client/modules/i18n/currency.js
  imports/plugins/core/orders/client/components/invoiceActions.js
  imports/plugins/core/ui/client/components/numericInput/numericInput.js
  imports/plugins/core/ui/client/components/textfield/textfield.js
  imports/plugins/included/default-theme/client/styles/main.less
  imports/plugins/included/default-theme/client/styles/numericInput.less
  imports/plugins/included/product-variant/components/variantForm.js
Labels: impact-major

#4054 Fix #3518: AddressBook to react
  imports/plugins/core/accounts/client/components/addressBook.js
  imports/plugins/core/accounts/client/components/addressBookForm.js
  imports/plugins/core/accounts/client/components/addressBookGrid.js
  imports/plugins/core/accounts/client/components/addressBookReview.js
  imports/plugins/core/accounts/client/containers/addressBookContainer.js
  imports/plugins/core/accounts/client/index.js
  imports/plugins/core/accounts/client/templates/addressBook/add/add.html
  imports/plugins/core/accounts/client/templates/addressBook/add/add.js
  imports/plugins/core/accounts/client/templates/addressBook/addressBook.html
  imports/plugins/core/accounts/client/templates/addressBook/addressBook.js
  imports/plugins/core/accounts/client/templates/addressBook/edit/edit.html
  imports/plugins/core/accounts/client/templates/addressBook/edit/edit.js
  imports/plugins/core/accounts/client/templates/addressBook/form/form.html
  imports/plugins/core/accounts/client/templates/addressBook/form/form.js
  imports/plugins/core/accounts/client/templates/addressBook/grid/grid.html
  imports/plugins/core/accounts/client/templates/addressBook/grid/grid.js
  imports/plugins/core/accounts/client/templates/addressBook/review/review.html
  imports/plugins/core/accounts/client/templates/addressBook/review/review.js
  imports/plugins/core/accounts/client/templates/profile/profile.html
  imports/plugins/core/accounts/client/templates/profile/profile.js
  imports/plugins/core/checkout/client/index.js
  imports/plugins/core/checkout/client/templates/checkout/addressBook/addressBook.html
  imports/plugins/core/checkout/client/templates/checkout/addressBook/addressBook.js
  imports/plugins/core/checkout/client/templates/checkout/checkout.html
  imports/plugins/core/orders/client/components/orderSummary.js
  imports/plugins/core/orders/client/components/orderTableColumn.js
  imports/plugins/core/orders/client/helpers/index.js
  imports/plugins/included/default-theme/client/styles/cart/addressBook.less
  imports/plugins/included/default-theme/client/styles/dashboard/orders.less
  imports/plugins/included/taxes-avalara/server/hooks/hooks.js
  imports/plugins/included/taxes-avalara/server/methods/taxCalc.js
  lib/collections/schemas/cart.js
  lib/collections/schemas/orders.js
  private/data/i18n/en.json
  server/methods/accounts/accounts.js
  server/methods/core/cart.js
  server/publications/collections/orders.js
Labels: impact-major, performance

#4067 Fix #4058: onClick to image too
  imports/plugins/included/product-detail-simple/client/components/childVariant.js
Labels: impact-major

#4091 Fix #2780: Styling shop slug box for Shopify
  imports/plugins/included/connectors-shopify/client/settings/shopify.html
  imports/plugins/included/connectors-shopify/client/settings/shopify.less
Labels: impact-minor, integrations

#4183 client side validation on address book
  imports/plugins/core/accounts/client/components/addressBook.js
  imports/plugins/core/accounts/client/components/addressBookForm.js
  imports/plugins/core/ui/client/components/textfield/textfield.js
Labels: release-blocker

#4156 Fix 4152: Currency as object
  client/modules/i18n/currency.js
  imports/plugins/core/ui/client/components/numericInput/numericInput.js
Labels: release-blocker

#4174 Correct some translation errors for i18n/it.json
  private/data/i18n/it.json
Labels: community, i18n + l10n

#4148 Fix for "Error when enabling Shopify inventory hooks"
  imports/plugins/included/connectors-shopify/server/methods/webhooks/webhooks.js
Labels: bug, impact-minor, integrations

#4082 (fix) Make shipping discount code case-insensitive
  imports/plugins/included/discount-codes/server/methods/methods.js
Labels: impact-minor

#4072 Fix #4057: Admin should have media editable
  imports/plugins/core/ui/client/components/media/mediaGallery.js
Labels: impact-major

#4065 Fix for "Product publication handle regex match issues with similar product handles
  server/publications/collections/product-publications.app-test.js
  server/publications/collections/product.js
Labels: impact-major

#4038 Fixes #4037: Paginate and Filter Orders Subscription on Admin Dashboard
  imports/plugins/core/orders/client/components/orderDashboard.js
  imports/plugins/core/orders/client/components/orderTable.js
  imports/plugins/core/orders/client/containers/orderDashboardContainer.js
  imports/plugins/core/orders/client/containers/orderSubscriptionContainer.js
  imports/plugins/core/orders/client/containers/orderSummaryContainer.js
  imports/plugins/core/ui/client/components/table/sortableTable.js
  server/publications/collections/orders.js
  server/publications/collections/reactiveAggregate.js
Labels: community

#3456 Accept Shop Data when Inviting Shop Owner
  imports/plugins/included/marketplace/client/components/inviteOwner.js
  server/methods/accounts/accounts.app-test.js
  server/methods/accounts/accounts.js
  server/methods/core/shop.js
  server/methods/core/shops.app-test.js
Labels: community

#4032 Fix #4009: inventory badge component added
  imports/plugins/core/ui/client/components/badge/index.js
  imports/plugins/core/ui/client/components/badge/inventoryBadge.js
  imports/plugins/core/ui/client/components/textfield/textfield.js
  imports/plugins/core/ui/client/containers/index.js
  imports/plugins/core/ui/client/containers/inventoryBadge.js
  imports/plugins/included/product-detail-simple/client/components/variant.js
  imports/plugins/included/product-variant/components/variantForm.js
Labels: impact-major
