Repository reactioncommerce/reaction, pull requests merged in 2019-04, with the labels that each got.

#5093 chore: security update for js-yaml
  package-lock.json
Labels: security

#5095 fix: catalog items performance
  imports/plugins/core/catalog/server/no-meteor/resolvers/CatalogProduct/index.js
  imports/plugins/core/catalog/server/no-meteor/resolvers/CatalogProductVariant/index.js
Labels: impact-critical, performance

#5099 Revert metrics prometheus
  imports/plugins/included/metrics-prometheus/client/index.js
  imports/plugins/included/metrics-prometheus/components/MetricsSettings.js
  imports/plugins/included/metrics-prometheus/components/index.js
  imports/plugins/included/metrics-prometheus/info.js
  imports/plugins/included/metrics-prometheus/register.js
  imports/plugins/included/metrics-prometheus/server/i18n/en.json
  imports/plugins/included/metrics-prometheus/server/i18n/index.js
  imports/plugins/included/metrics-prometheus/server/index.js
  imports/plugins/included/metrics-prometheus/server/no-meteor/startup.js
  package-lock.json
  package.json
Labels: operator-ui

#5096 fix: orders performance
  imports/plugins/core/core/server/publications/collections/orders.js
  imports/plugins/core/orders/client/components/orderDashboard.js
  imports/plugins/core/orders/client/components/orderFilter.js
  imports/plugins/core/orders/client/components/orderTable.js
  imports/plugins/core/orders/client/containers/orderDashboardContainer.js
  imports/plugins/core/orders/client/index.js
  imports/plugins/core/orders/client/templates/list/pdf.js
  imports/plugins/core/orders/server/no-meteor/startup.js
Labels: impact-major, performance

#5108 chore: ignore js-yaml vuln for 30 days
  .snyk
Labels: security

#5118 fix: include submodule bare repos in docker build context
  .dockerignore
Labels: bug
