Repository reactioncommerce/reaction, pull requests merged in 2019-11, with the labels that each got.

#5744 fix: password-reset route not working correctly
  imports/plugins/core/accounts/client/components/login.js
  imports/plugins/core/accounts/client/containers/updatePassword.js
  imports/plugins/core/graphql/lib/helpers/initApollo.js
  package-lock.json
Labels: core-bug, next-release

#5715 [Fix] Create and Delete navigation item mutations
  imports/node-app/plugins/navigation/mutations/createNavigationItem.js
  imports/node-app/plugins/navigation/mutations/deleteNavigationItem.js
  imports/node-app/plugins/navigation/mutations/deleteNavigationItem.test.js
  imports/node-app/plugins/navigation/queries/navigationTreeById.js
  imports/node-app/plugins/navigation/queries/navigationTreeById.test.js
Labels: community

#5768 feat: add updateProduct and updateProductVariant mutations for 3.0
  package-lock.json
  package.json
  src/core-services/catalog/startup.js
  src/core-services/core/i18n/en.json
  src/core-services/product/mutations/index.js
  src/core-services/product/mutations/updateProduct.js
  src/core-services/product/mutations/updateProductVariant.js
  src/core-services/product/resolvers/Mutation/index.js
  src/core-services/product/resolvers/Mutation/updateProduct.js
  src/core-services/product/resolvers/Mutation/updateProductVariant.js
  src/core-services/product/schemas/product.graphql
  tests/integration/api/mutations/updateProduct/updateProduct.test.js
  tests/integration/api/mutations/updateProduct/updateProductMutation.graphql
  tests/integration/api/mutations/updateProduct/updateProductVariantMutation.graphql
Labels: 3.0
