Repository reactioncommerce/reaction, pull requests merged in 2019-09, with the labels that each got.

#5516 Fixes #5513 - checkout shipping methods
  imports/collections/schemas/shipping.js
Labels: bug

#5511 Add Integration Test for orderById GraphQL query
  tests/integration/api/queries/orderById/orderById.test.js
Labels: testing

#5502 fix(bulktag): info inline alert should autoclose
  imports/plugins/included/product-admin/client/components/ProductTable.js
Labels: reaction-admin

#5483 feat: Add Orders GraphQL query
  imports/plugins/core/orders/server/no-meteor/queries/index.js
  imports/plugins/core/orders/server/no-meteor/queries/orders.js
  imports/plugins/core/orders/server/no-meteor/resolvers/Query/index.js
  imports/plugins/core/orders/server/no-meteor/resolvers/Query/orders.js
  imports/plugins/core/orders/server/no-meteor/resolvers/index.js
  imports/plugins/core/orders/server/no-meteor/schemas/schema.graphql
Labels: reaction-admin

#5485 feature: manage product tags in bulk
  imports/plugins/core/product/server/no-meteor/mutations/addTagsToProducts.js
  imports/plugins/core/product/server/no-meteor/mutations/addTagsToProducts.test.js
  imports/plugins/core/product/server/no-meteor/mutations/removeTagsFromProducts.js
  imports/plugins/core/product/server/no-meteor/mutations/removeTagsFromProducts.test.js
  imports/plugins/core/ui/client/components/forms/form.js
  imports/plugins/core/ui/client/components/multiselect/multiselect.js
  imports/plugins/included/default-theme/client/styles/main.less
  imports/plugins/included/product-admin/client/components/FilterByFileCard.js
  imports/plugins/included/product-admin/client/components/ProductTable.js
  imports/plugins/included/product-admin/client/components/TagSelector/Notifications.js
  imports/plugins/included/product-admin/client/components/TagSelector/TagSelector.js
  imports/plugins/included/product-admin/client/components/TagSelector/helpers.js
  imports/plugins/included/product-admin/client/components/TagSelector/index.js
  imports/plugins/included/product-admin/client/components/TagSelector/mutations.js
  imports/plugins/included/product-admin/client/components/TagSelector/queries.js
  imports/plugins/included/product-admin/server/i18n/en.json
  imports/plugins/included/product-variant/components/productGrid.js
  imports/plugins/included/product-variant/components/products.js
  imports/test-utils/helpers/mockContext.js
  package-lock.json
  package.json
Labels: reaction-admin
