Repository reactioncommerce/reaction, pull requests merged in 2019-08, with the labels that each got.

#5395 Feat #5366 show filter count
  imports/plugins/included/product-admin/client/components/ProductTable.js
  imports/plugins/included/product-admin/server/i18n/en.json
  imports/plugins/included/product-variant/components/productGrid.js
Labels: reaction-admin

#5407 feat(producttable): add isvisible/hidden icons
  imports/plugins/included/product-variant/components/productGridItems.js
Labels: reaction-admin

#5427 Update Apollo packages to support hooks
  imports/plugins/core/graphql/lib/hocs/withCatalogItems.test.js
  imports/plugins/core/graphql/lib/hocs/withPrimaryShopId.test.js
  imports/plugins/core/graphql/lib/hocs/withShopId.test.js
  imports/plugins/core/graphql/lib/hocs/withTagId.test.js
  package-lock.json
  package.json
  tests/integration/api/mutations/updateSimpleInventory/__snapshots__/updateSimpleInventory.test.js.snap
  tests/integration/api/queries/simpleInventory/__snapshots__/simpleInventory.test.js.snap
Labels: chore

#5406 Feat #5379 integrate catalyst button
  imports/plugins/core/accounts/client/components/signIn.js
  imports/plugins/core/address/client/components/ShopAddressValidationSettings.js
  imports/plugins/core/router/client/appComponents.js
  imports/plugins/core/tags/client/components/TagDataTable.js
  imports/plugins/core/tags/client/components/TagForm.js
  imports/plugins/core/tags/client/components/TagToolbar.js
  imports/plugins/core/tags/client/pages/TagSettingsPageWithData.js
  imports/plugins/core/taxes/client/components/GeneralTaxSettings.js
  imports/plugins/included/shipping-rates/components/ShippingMethodForm.js
  imports/plugins/included/sitemap-generator/client/components/sitemap-settings.js
Labels: reaction-admin

#5405 refactor: refunds section of Orders 2.0
  imports/plugins/core/orders/client/components/Order.js
  imports/plugins/core/orders/client/components/OrderCardFulfillmentGroupItem.js
  imports/plugins/core/orders/client/components/OrderCardFulfillmentGroupStatusButton.js
  imports/plugins/core/orders/client/components/OrderCardFulfillmentGroups.js
  imports/plugins/core/orders/client/components/OrderHeader.js
  imports/plugins/core/orders/client/components/OrderPayment.js
  imports/plugins/core/orders/client/components/OrderPayments.js
  imports/plugins/core/orders/client/components/OrderPreviousRefunds.js
  imports/plugins/core/orders/client/components/OrderRefunds.js
  imports/plugins/core/orders/client/graphql/fragments/orderCommon.js
  imports/plugins/core/orders/client/graphql/mutations/approveOrderPayments.js
  imports/plugins/core/orders/client/graphql/mutations/createRefund.js
  imports/plugins/core/orders/server/i18n/en.json
  imports/plugins/core/orders/server/no-meteor/mutations/__snapshots__/createRefund.test.js.snap
  imports/plugins/core/orders/server/no-meteor/mutations/createRefund.js
  imports/plugins/core/payments/server/no-meteor/resolvers/PaymentMethod/index.js
  imports/plugins/core/payments/server/no-meteor/resolvers/index.js
  package-lock.json
  package.json
Labels: reaction-admin

#5404 Feature: add bulk mutations to manage products and tags
  imports/plugins/core/product/server/no-meteor/mutations/addTagsToProducts.js
  imports/plugins/core/product/server/no-meteor/mutations/addTagsToProducts.test.js
  imports/plugins/core/product/server/no-meteor/mutations/index.js
  imports/plugins/core/product/server/no-meteor/mutations/removeTagsFromProducts.js
  imports/plugins/core/product/server/no-meteor/mutations/removeTagsFromProducts.test.js
  imports/plugins/core/product/server/no-meteor/register.js
  imports/plugins/core/product/server/no-meteor/resolvers/Mutation/addTagsToProducts.js
  imports/plugins/core/product/server/no-meteor/resolvers/Mutation/index.js
  imports/plugins/core/product/server/no-meteor/resolvers/Mutation/removeTagsFromProducts.js
  imports/plugins/core/product/server/no-meteor/resolvers/index.js
  imports/plugins/core/product/server/no-meteor/schemas/schema.graphql
  imports/plugins/core/product/server/no-meteor/utils/executeBulkOperation.js
  imports/plugins/included/product-variant/components/productGridItems.js
  imports/test-utils/helpers/mockContext.js
Labels: reaction-admin

#5463 Fix console warnings
  imports/plugins/included/product-variant/components/productGrid.js
  imports/plugins/included/product-variant/components/products.js
Labels: reaction-admin

#5468 fix(product table): style the product table as close as possible
  imports/plugins/included/product-variant/components/productGrid.js
  imports/plugins/included/product-variant/components/productGridItems.js
Labels: reaction-admin

#5459 test: add integration test for primaryShop query
  tests/integration/api/queries/primaryShop/primaryShop.test.js
Labels: testing

#5158 refactor: update Reaction Admin Orders panel
  imports/meteor-app-tests/orders.app-test.js
  imports/plugins/core/checkout/client/components/productImage.js
  imports/plugins/core/checkout/client/index.js
  imports/plugins/core/core/server/startup/rate-limits.js
  imports/plugins/core/orders/client/components/OrderCardFulfillmentGroupStatusButton.js
  imports/plugins/core/orders/client/components/OrderPaymentMeteor.js
  imports/plugins/core/orders/client/components/OrderPayments.js
  imports/plugins/core/orders/client/components/invoice.js
  imports/plugins/core/orders/client/components/lineItems.js
  imports/plugins/core/orders/client/components/orderBulkActionsBar.js
  imports/plugins/core/orders/client/components/orderDashboard.js
  imports/plugins/core/orders/client/containers/invoiceContainer.js
  imports/plugins/core/orders/client/containers/orderSummaryContainer.js
  imports/plugins/core/orders/client/containers/orderTableContainer.js
  imports/plugins/core/orders/client/graphql/approveOrderPayments.graphql
  imports/plugins/core/orders/client/graphql/captureOrderPayments.graphql
  imports/plugins/core/orders/client/graphql/index.js
  imports/plugins/core/orders/client/graphql/updateOrderFulfillmentGroup.graphql
  imports/plugins/core/orders/client/helpers/index.js
  imports/plugins/core/orders/client/index.js
  imports/plugins/core/orders/client/templates/list/summary.html
  imports/plugins/core/orders/client/templates/list/summary.js
  imports/plugins/core/orders/client/templates/orders.html
  imports/plugins/core/orders/client/templates/orders.js
  imports/plugins/core/orders/client/templates/workflow/shippingTracking.html
  imports/plugins/core/orders/client/templates/workflow/shippingTracking.js
  imports/plugins/core/orders/client/templates/workflow/workflow.html
  imports/plugins/core/orders/client/templates/workflow/workflow.js
  imports/plugins/core/orders/server/index.js
  imports/plugins/core/orders/server/methods/approvePayment.js
  imports/plugins/core/orders/server/methods/cancelOrder.js
  imports/plugins/core/orders/server/methods/createRefund.js
  imports/plugins/core/orders/server/methods/index.js
  imports/plugins/core/orders/server/methods/listRefunds.js
  imports/plugins/core/orders/server/methods/makeAdjustmentsToInvoice.js
  imports/plugins/core/orders/server/methods/refundItems.js
  imports/plugins/core/orders/server/methods/sendNotification.js
  imports/plugins/core/orders/server/methods/shipmentDelivered.js
  imports/plugins/core/orders/server/methods/shipmentLabeled.js
  imports/plugins/core/orders/server/methods/shipmentPacked.js
  imports/plugins/core/orders/server/methods/shipmentPicked.js
  imports/plugins/core/orders/server/methods/shipmentShipped.js
  imports/plugins/core/orders/server/methods/updateHistory.js
  imports/plugins/core/orders/server/no-meteor/register.js
  imports/plugins/core/shipping/server/index.js
  imports/plugins/core/shipping/server/methods/index.js
  imports/plugins/core/shipping/server/methods/statusRefresh.js
Labels: reaction-admin

#5504 fix(card): remove raised shadow from Quick Edit card
  imports/plugins/included/product-admin/client/components/ProductTable.js
Labels: reaction-admin

#5507 fix(card): remove raised shadow
  imports/plugins/included/product-admin/client/components/ProductTable.js
Labels: reaction-admin
